/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from 'react';

export const Index: Record<string, any> = {
  'webamp-player': {
    name: 'webamp-player',
    description: 'A Winamp music player component using Webamp',
    type: 'registry:component',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/components/webamp-player.tsx',
        type: 'registry:component',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/components/webamp-player.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
};
