import { exec, execFile } from 'child_process';
import { existsSync, promises as fs } from 'fs';
import path from 'path';
import { rimraf } from 'rimraf';
import { registrySchema } from 'shadcn/schema';

const REGISTRY_PATH = 'registry';

async function buildRegistryIndex() {
  let index = `/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

import * as React from "react"

export const Index: Record<string, any> = {`;

  // Import the registry from the default location.
  const { registry: importedRegistry } = await import(`../registry/index`);

  // Validate the registry schema.
  const parseResult = registrySchema.safeParse(importedRegistry);
  if (!parseResult.success) {
    console.error(`❌ Registry validation failed:`);
    console.error(parseResult.error.format());
    throw new Error(`Invalid registry schema`);
  }

  const registry = parseResult.data;

  for (const item of registry.items) {
    const files =
      item.files?.map((file) => ({
        path: typeof file === 'string' ? file : file.path,
        type: typeof file === 'string' ? item.type : file.type,
        target: typeof file === 'string' ? undefined : file.target,
      })) ?? [];

    if (files.length === 0) {
      continue;
    }

    const componentPath = item.files?.[0]?.path
      ? `@/registry/${item.files[0].path}`
      : '';

    index += `
  "${item.name}": {
    name: "${item.name}",
    description: "${item.description ?? ''}",
    type: "${item.type}",
    registryDependencies: ${JSON.stringify(item.registryDependencies)},
    files: [${files.map((file) => {
      const filePath = `registry/${file.path}`;
      return `{
      path: "${filePath}",
      type: "${file.type}",
      target: "${file.target ?? ''}"
    }`;
    })}],
    component: ${
      componentPath
        ? `React.lazy(async () => {
      const mod = await import("${componentPath}")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    })`
        : 'null'
    },
    categories: ${JSON.stringify(item.categories)},
    meta: ${JSON.stringify(item.meta)},
  },`;
  }

  index += `
}`;

  console.log(`#️⃣  Built registry index with ${registry.items.length} items`);

  // Write unified index.
  rimraf.sync(path.join(process.cwd(), 'registry/__index__.tsx'));
  await fs.writeFile(path.join(process.cwd(), 'registry/__index__.tsx'), index);
}

async function buildRegistryJsonFile() {
  // 1. Import the registry.
  const { registry: importedRegistry } = await import(`../registry/index`);

  // 2. Validate the registry schema.
  const parseResult = registrySchema.safeParse(importedRegistry);
  if (!parseResult.success) {
    console.error(`❌ Registry validation failed:`);
    console.error(parseResult.error.format());
    throw new Error(`Invalid registry schema`);
  }

  const registry = parseResult.data;

  // 3. Fix the path for registry items.
  const fixedRegistry = {
    ...registry,
    items: registry.items.map((item) => {
      const files = item.files?.map((file) => {
        return {
          ...file,
          path: `registry/${file.path}`,
        };
      });

      return {
        ...item,
        files,
      };
    }),
  };

  // 3. Create the output directory and write registry.json.
  const outputDir = path.join(process.cwd(), 'public/r');
  await fs.mkdir(outputDir, { recursive: true });

  // 4. Write registry.json to output directory and format it.
  const registryJsonPath = path.join(outputDir, 'registry.json');
  await fs.writeFile(registryJsonPath, JSON.stringify(fixedRegistry, null, 2));
  await new Promise<void>((resolve, reject) => {
    execFile('prettier', ['--write', registryJsonPath], (error) => {
      if (error) {
        reject(error);
      } else {
        resolve();
      }
    });
  });

  // 5. Write temporary registry file needed by shadcn build.
  const tempRegistryPath = path.join(process.cwd(), 'registry.json');
  await fs.writeFile(tempRegistryPath, JSON.stringify(fixedRegistry, null, 2));
}

async function buildRegistry() {
  return new Promise((resolve, reject) => {
    const outputPath = 'public/r';
    const process = exec(
      `pnpm dlx shadcn build registry.json --output ${outputPath}`
    );

    process.on('exit', (code) => {
      if (code === 0) {
        resolve(undefined);
      } else {
        reject(new Error(`Process exited with code ${code}`));
      }
    });
  });
}

try {
  console.log('🎨 Building registry for default style...');

  // Build registry index.
  console.log('\n📂 Building registry/__index__.tsx...');
  await buildRegistryIndex();

  console.log('\n📦 Processing registry...');

  console.log('💅 Building registry.json...');
  await buildRegistryJsonFile();

  console.log('🏗️ Building registry files...');
  await buildRegistry();

  // Clean up intermediate files.
  console.log('\n🧹 Cleaning up intermediate files...');
  if (existsSync(path.join(process.cwd(), 'registry.json'))) {
    await fs.unlink(path.join(process.cwd(), 'registry.json'));
  }

  console.log('\n✅ Build complete!');
} catch (error) {
  console.error(error);
  process.exit(1);
}
